// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace EFModel.Models;

public partial class DatabaseContext : DbContext
{
    public DatabaseContext(DbContextOptions<DatabaseContext> options)
        : base(options)
    {
    }

    public virtual DbSet<GameTownGame> GameTownGames { get; set; }

    public virtual DbSet<Rawgdeveloper> Rawgdevelopers { get; set; }

    public virtual DbSet<Rawggame> Rawggames { get; set; }

    public virtual DbSet<Rawggenre> Rawggenres { get; set; }

    public virtual DbSet<Rawgscreenshot> Rawgscreenshots { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<GameTownGame>(entity =>
        {
            entity.ToTable("GameTownGame");

            entity.Property(e => e.Id).HasDefaultValueSql("newid()");
            entity.Property(e => e.HowTo).IsRequired();
            entity.Property(e => e.RawggameId).HasColumnName("RAWGGameId");
            entity.Property(e => e.Title)
                .IsRequired()
                .HasMaxLength(500);
            entity.Property(e => e.Url)
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnName("URL");

            entity.HasOne(d => d.Rawggame).WithMany(p => p.GameTownGames)
                .HasForeignKey(d => d.RawggameId)
                .HasConstraintName("FK_GameTownGame_Games");
        });

        modelBuilder.Entity<Rawgdeveloper>(entity =>
        {
            entity.ToTable("RAWGDevelopers");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.GamesCount).HasColumnName("games_count");
            entity.Property(e => e.ImageBackground)
                .HasMaxLength(500)
                .HasColumnName("image_background");
            entity.Property(e => e.Name)
                .HasMaxLength(255)
                .HasColumnName("name");
            entity.Property(e => e.Slug)
                .HasMaxLength(255)
                .HasColumnName("slug");
        });

        modelBuilder.Entity<Rawggame>(entity =>
        {
            entity.ToTable("RAWGGames");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.AchievementsCount).HasColumnName("achievements_count");
            entity.Property(e => e.AdditionsCount).HasColumnName("additions_count");
            entity.Property(e => e.BackgroundImage)
                .HasMaxLength(500)
                .HasColumnName("background_image");
            entity.Property(e => e.BackgroundImageAdditional)
                .HasMaxLength(500)
                .HasColumnName("background_image_additional");
            entity.Property(e => e.CreatorsCount).HasColumnName("creators_count");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasColumnName("description");
            entity.Property(e => e.DominantColor)
                .HasMaxLength(10)
                .HasColumnName("dominant_color");
            entity.Property(e => e.GameSeriesCount).HasColumnName("game_series_count");
            entity.Property(e => e.Metacritic).HasColumnName("metacritic");
            entity.Property(e => e.MetacriticUrl)
                .HasMaxLength(500)
                .HasColumnName("metacritic_url");
            entity.Property(e => e.MoviesCount).HasColumnName("movies_count");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("name");
            entity.Property(e => e.NameOriginal)
                .HasMaxLength(255)
                .HasColumnName("name_original");
            entity.Property(e => e.ParentAchievementsCount).HasColumnName("parent_achievements_count");
            entity.Property(e => e.ParentsCount).HasColumnName("parents_count");
            entity.Property(e => e.Playtime).HasColumnName("playtime");
            entity.Property(e => e.Rating).HasColumnName("rating");
            entity.Property(e => e.RatingTop).HasColumnName("rating_top");
            entity.Property(e => e.RatingsCount).HasColumnName("ratings_count");
            entity.Property(e => e.RedditCount).HasColumnName("reddit_count");
            entity.Property(e => e.RedditUrl)
                .HasMaxLength(500)
                .HasColumnName("reddit_url");
            entity.Property(e => e.Released)
                .HasColumnType("date")
                .HasColumnName("released");
            entity.Property(e => e.ReviewsCount).HasColumnName("reviews_count");
            entity.Property(e => e.ReviewsTextCount).HasColumnName("reviews_text_count");
            entity.Property(e => e.SaturatedColor)
                .HasMaxLength(10)
                .HasColumnName("saturated_color");
            entity.Property(e => e.ScreenshotsCount).HasColumnName("screenshots_count");
            entity.Property(e => e.Slug)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("slug");
            entity.Property(e => e.SuggestionsCount).HasColumnName("suggestions_count");
            entity.Property(e => e.Tba).HasColumnName("tba");
            entity.Property(e => e.TwitchCount).HasColumnName("twitch_count");
            entity.Property(e => e.Updated)
                .HasColumnType("datetime")
                .HasColumnName("updated");
            entity.Property(e => e.Website)
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnName("website");
            entity.Property(e => e.YoutubeCount).HasColumnName("youtube_count");

            entity.HasMany(d => d.Developers).WithMany(p => p.Games)
                .UsingEntity<Dictionary<string, object>>(
                    "RawggamesDeveloper",
                    r => r.HasOne<Rawgdeveloper>().WithMany()
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.ClientSetNull),
                    l => l.HasOne<Rawggame>().WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.ClientSetNull),
                    j =>
                    {
                        j.HasKey("GameId", "DeveloperId");
                        j.ToTable("RAWGGames_Developers");
                        j.IndexerProperty<int>("GameId").HasColumnName("game_id");
                        j.IndexerProperty<int>("DeveloperId").HasColumnName("developer_id");
                    });

            entity.HasMany(d => d.Genres).WithMany(p => p.Games)
                .UsingEntity<Dictionary<string, object>>(
                    "RawggamesGenre",
                    r => r.HasOne<Rawggenre>().WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.ClientSetNull),
                    l => l.HasOne<Rawggame>().WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.ClientSetNull),
                    j =>
                    {
                        j.HasKey("GameId", "GenreId");
                        j.ToTable("RAWGGames_Genres");
                        j.IndexerProperty<int>("GameId").HasColumnName("game_id");
                        j.IndexerProperty<int>("GenreId").HasColumnName("genre_id");
                    });

            entity.HasMany(d => d.Screenshots).WithMany(p => p.Games)
                .UsingEntity<Dictionary<string, object>>(
                    "RawggamesScreenshot",
                    r => r.HasOne<Rawgscreenshot>().WithMany()
                        .HasForeignKey("Screenshotid")
                        .OnDelete(DeleteBehavior.ClientSetNull),
                    l => l.HasOne<Rawggame>().WithMany()
                        .HasForeignKey("Gameid")
                        .OnDelete(DeleteBehavior.ClientSetNull),
                    j =>
                    {
                        j.HasKey("Gameid", "Screenshotid");
                        j.ToTable("RAWGGames_Screenshots");
                        j.IndexerProperty<int>("Gameid").HasColumnName("gameid");
                        j.IndexerProperty<int>("Screenshotid").HasColumnName("screenshotid");
                    });
        });

        modelBuilder.Entity<Rawggenre>(entity =>
        {
            entity.ToTable("RAWGGenres");

            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.ImageBackground)
                .HasMaxLength(500)
                .HasColumnName("image_background");
            entity.Property(e => e.Name)
                .HasMaxLength(255)
                .HasColumnName("name");
            entity.Property(e => e.Slug)
                .HasMaxLength(255)
                .HasColumnName("slug");
        });

        modelBuilder.Entity<Rawgscreenshot>(entity =>
        {
            entity.ToTable("RAWGScreenshots");

            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.Height).HasColumnName("height");
            entity.Property(e => e.Image)
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnName("image");
            entity.Property(e => e.IsDeleted).HasColumnName("is_deleted");
            entity.Property(e => e.Width).HasColumnName("width");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}