// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace EFModel.Models;

public partial class DatabaseContext : DbContext
{
    public DatabaseContext(DbContextOptions<DatabaseContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Developer> Developers { get; set; }

    public virtual DbSet<Game> Games { get; set; }

    public virtual DbSet<Genre> Genres { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Developer>(entity =>
        {
            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.GamesCount).HasColumnName("games_count");
            entity.Property(e => e.ImageBackground)
                .HasMaxLength(500)
                .HasColumnName("image_background");
            entity.Property(e => e.Name)
                .HasMaxLength(255)
                .HasColumnName("name");
            entity.Property(e => e.Slug)
                .HasMaxLength(255)
                .HasColumnName("slug");
        });

        modelBuilder.Entity<Game>(entity =>
        {
            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.AchievementsCount).HasColumnName("achievements_count");
            entity.Property(e => e.AdditionsCount).HasColumnName("additions_count");
            entity.Property(e => e.BackgroundImage)
                .HasMaxLength(500)
                .HasColumnName("background_image");
            entity.Property(e => e.BackgroundImageAdditional)
                .HasMaxLength(500)
                .HasColumnName("background_image_additional");
            entity.Property(e => e.CreatorsCount).HasColumnName("creators_count");
            entity.Property(e => e.Description)
                .IsRequired()
                .HasColumnName("description");
            entity.Property(e => e.DominantColor)
                .HasMaxLength(10)
                .HasColumnName("dominant_color");
            entity.Property(e => e.GameSeriesCount).HasColumnName("game_series_count");
            entity.Property(e => e.Metacritic).HasColumnName("metacritic");
            entity.Property(e => e.MetacriticUrl)
                .HasMaxLength(500)
                .HasColumnName("metacritic_url");
            entity.Property(e => e.MoviesCount).HasColumnName("movies_count");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("name");
            entity.Property(e => e.NameOriginal)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("name_original");
            entity.Property(e => e.ParentAchievementsCount).HasColumnName("parent_achievements_count");
            entity.Property(e => e.ParentsCount).HasColumnName("parents_count");
            entity.Property(e => e.Playtime).HasColumnName("playtime");
            entity.Property(e => e.Rating).HasColumnName("rating");
            entity.Property(e => e.RatingTop).HasColumnName("rating_top");
            entity.Property(e => e.RatingsCount).HasColumnName("ratings_count");
            entity.Property(e => e.RedditCount).HasColumnName("reddit_count");
            entity.Property(e => e.RedditUrl)
                .HasMaxLength(500)
                .HasColumnName("reddit_url");
            entity.Property(e => e.Released)
                .HasColumnType("date")
                .HasColumnName("released");
            entity.Property(e => e.ReviewsCount).HasColumnName("reviews_count");
            entity.Property(e => e.ReviewsTextCount).HasColumnName("reviews_text_count");
            entity.Property(e => e.SaturatedColor)
                .HasMaxLength(10)
                .HasColumnName("saturated_color");
            entity.Property(e => e.ScreenshotsCount).HasColumnName("screenshots_count");
            entity.Property(e => e.Slug)
                .IsRequired()
                .HasMaxLength(255)
                .HasColumnName("slug");
            entity.Property(e => e.SuggestionsCount).HasColumnName("suggestions_count");
            entity.Property(e => e.Tba).HasColumnName("tba");
            entity.Property(e => e.TwitchCount).HasColumnName("twitch_count");
            entity.Property(e => e.Updated)
                .HasColumnType("datetime")
                .HasColumnName("updated");
            entity.Property(e => e.Website)
                .IsRequired()
                .HasMaxLength(500)
                .HasColumnName("website");
            entity.Property(e => e.YoutubeCount).HasColumnName("youtube_count");

            entity.HasMany(d => d.Developers).WithMany(p => p.Games)
                .UsingEntity<Dictionary<string, object>>(
                    "GameDeveloper",
                    r => r.HasOne<Developer>().WithMany()
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.ClientSetNull),
                    l => l.HasOne<Game>().WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.ClientSetNull),
                    j =>
                    {
                        j.HasKey("GameId", "DeveloperId");
                        j.ToTable("GameDevelopers");
                        j.IndexerProperty<int>("GameId").HasColumnName("game_id");
                        j.IndexerProperty<int>("DeveloperId").HasColumnName("developer_id");
                    });

            entity.HasMany(d => d.Genres).WithMany(p => p.Games)
                .UsingEntity<Dictionary<string, object>>(
                    "GameGenre",
                    r => r.HasOne<Genre>().WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.ClientSetNull),
                    l => l.HasOne<Game>().WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.ClientSetNull),
                    j =>
                    {
                        j.HasKey("GameId", "GenreId");
                        j.ToTable("GameGenres");
                        j.IndexerProperty<int>("GameId").HasColumnName("game_id");
                        j.IndexerProperty<int>("GenreId").HasColumnName("genre_id");
                    });
        });

        modelBuilder.Entity<Genre>(entity =>
        {
            entity.Property(e => e.Id)
                .ValueGeneratedNever()
                .HasColumnName("id");
            entity.Property(e => e.ImageBackground)
                .HasMaxLength(500)
                .HasColumnName("image_background");
            entity.Property(e => e.Name)
                .HasMaxLength(255)
                .HasColumnName("name");
            entity.Property(e => e.Slug)
                .HasMaxLength(255)
                .HasColumnName("slug");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}