// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFModel.Models;

public partial class GameTownUser
{
    public Guid Id { get; set; }

    public string PasswordHash { get; set; }

    public string Salt { get; set; }

    public string Username { get; set; }

    public string DisplayName { get; set; }

    public bool IsActive { get; set; }

    public string Notes { get; set; }

    public DateTime CreatedAt { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? LastModifiedAt { get; set; }

    public string LastModifiedBy { get; set; }

    public virtual ICollection<GameTownRole> Apiroles { get; set; } = new List<GameTownRole>();
}