// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFModel.Models;

public partial class GameTownRole
{
    public Guid Id { get; set; }

    public string Role { get; set; }

    public string CreatedBy { get; set; }

    public DateTime CreatedDate { get; set; }

    public string ModifiedBy { get; set; }

    public DateTime ModifiedDate { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<GameTownUser> Apiusers { get; set; } = new List<GameTownUser>();
}