// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFModel.Models;

public partial class GameTownGame
{
    public Guid Id { get; set; }

    public string Title { get; set; }

    public string HowTo { get; set; }

    public int? RawggameId { get; set; }

    public string Url { get; set; }

    public virtual Rawggame Rawggame { get; set; }
}