CREATE TABLE [Games] (
    [id] INT PRIMARY KEY,
    [slug] NVARCHAR(255) NOT NULL,
    [name] NVARCHAR(255) NOT NULL,
    [name_original] NVARCHAR(255) NOT NULL,
    [description] NVARCHAR(MAX) NOT NULL,
    [metacritic] INT,
    [released] DATE,
    [tba] BIT,
    [updated] DATETIME,
    [background_image] NVARCHAR(500),
    [background_image_additional] NVARCHAR(500),
    [website] NVARCHAR(500) NOT NULL,
    [rating] FLOAT,
    [rating_top] INT,
    [playtime] INT,
    [screenshots_count] INT,
    [movies_count] INT,
    [creators_count] INT,
    [achievements_count] INT,
    [parent_achievements_count] INT,
    [reddit_url] NVARCHAR(500),
    [reddit_count] INT,
    [twitch_count] INT,
    [youtube_count] INT,
    [reviews_text_count] INT,
    [ratings_count] INT,
    [suggestions_count] INT,
    [metacritic_url] NVARCHAR(500),
    [parents_count] INT,
    [additions_count] INT,
    [game_series_count] INT,
    [reviews_count] INT,
    [saturated_color] NVARCHAR(10),
    [dominant_color] NVARCHAR(10)
);