CREATE TABLE [dbo].[GameTownRoles]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT(NEWID()),
	[Role] NVARCHAR(50) NOT NULL,
	[CreatedBy] NVARCHAR(50) NOT NULL,
	[CreatedDate] DATETIME2 DEFAULT GETDATE() NOT NULL,
	[ModifiedBy] NVARCHAR(50) NOT NULL,
	[ModifiedDate] DATETIME2 DEFAULT GETDATE() NOT NULL,
	[IsActive] BIT DEFAULT 1 NOT NULL
)
