CREATE TABLE [dbo].[GameTownUsers_Roles]
(
	APIUserId UNIQUEIDENTIFIER NOT NULL,
    APIRoleId UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT PK_APIUsers_APIRoles PRIMARY KEY (APIUserId, APIRoleId),
    CONSTRAINT FK_APIUsers_APIRoles_APIUserId FOREIGN KEY (APIUserId) REFERENCES dbo.GameTownUsers(Id),
    CONSTRAINT FK_APIUsers_APIRoles_APIRoleId FOREIGN KEY (APIRoleId) REFERENCES dbo.GameTownRoles(Id)
)
