CREATE TABLE [dbo].[RefreshTokens]
(
	[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT(NEWID()),
	[Token] NVARCHAR(512) NOT NULL,
	[ExpiresAt] DATETIME2 NOT NULL,
	[IsRevoked] BIT NOT NULL DEFAULT(0),
	[CreatedAt] DATETIME2 NOT NULL DEFAULT(GETDATE()),
	[UserId] UNIQUEIDENTIFIER NOT NULL
	CONSTRAINT [FK_RefreshTokens_Users] FOREIGN KEY ([UserId]) REFERENCES [dbo].[GameTownUsers]([Id]) ON DELETE CASCADE
)
